baseurl = "/"
languageCode = "en-us"
title = "Estelle & Josh — Two people who like each other"
baseURL = "https://estelle.and.dzello.com/"
theme = ["reveal-hugo"]

[params]
description = "A compilation of our favorite stories and photos from when we met until now."
og_image = "https://estelle.and.dzello.com/images/assets/heart-frame.png"
og_image_width = 1600
og_image_height = 945

[params.reveal_hugo]
margin = 0.2
transition = "slide"
transition_speed = "fast"

[params.reveal_hugo.templates.yellow]
background = "#f6f195"
transition = "slide-in fade-out"

[params.reveal_hugo.templates.blue]
background = "#a5e2fd"
transition = "slide-in fade-out"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
